version: "3.8"
services:
  suitecrm:
    build: ./suitecrm/
    volumes:
      #SuiteCRM Application Folder
      - apache_www_html:/var/www/html
      #SuiteCRM Log Folder
      - suitecrm_logs:/var/www/html/SuiteCRM/logs
      - apache_logs:/var/log/apache2/  
    environment:
      - ROOT_URL=${ROOT_URL}
      - MARIADB_USER=suitecrm
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=suitecrm
      - MARIADB_HOST=mariadb_crm
      - DEFAULT_ADMIN_USER=${DEFAULT_ADMIN_USER}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - INSTALL_DEMO_DATA=${INSTALL_DEMO_DATA}
      - ENV_NAME=${ENV_NAME}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM_ADDRESS=suitecrm@example.com
      - SMTP_FROM_NAME=SuiteCRM
    ports:
      - "8080:80"
    depends_on:
      - mariadb_crm

  mariadb_crm:
    image: mariadb:10.7
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=suitecrm
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=suitecrm
    volumes:
      - mariadb_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb_crm
    ports:
      - 8181:80
    environment:
      - PMA_HOST=mariadb_crm
      - PMA_USER=suitecrm
      - PMA_PASSWORD=${MARIADB_PASSWORD}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
    depends_on:
      - mariadb_crm

  mailhog:
    image: cd2team/mailhog
    init: true
    ports:
      - 8025:8025
    
volumes:
  mariadb_data:
  apache_logs:
  apache_www_html:
  suitecrm_logs:
